### ISSUE TITLE
version 2.02 doesn't play with eF 3.2.0 MS store version

### ISSUE THREAD

**Issue by malsalt** [CadiLillian/eFootball-FPS-Limit-and-VSync-Patcher#4] opened 2023-12-21 21:23 UTC
Dumped the game but once i put the patch and the eF .exe file it on the same folder -tried also putting both files on desktop, the patch doesn't show up on screen just a tool tip on the top left side on screen with "GLFW message wi..." text for a fraction of a second, exactly the same behavior shown in "1.12 fail to unlock MS Store/Xbox 2.60 #1 recording. The patch appears to be opened in Windows 11 background processes, quite active with around 6% constant cpu usage for a few minutes then, closes by itself. 

I have also set the eF .exe file to full control permissions on all groups / users with no results. 

Later test: after clicking multiple times on the icon, after a few minutes while sitting in background processes, the UI popped out of nowhere and managed to unlock the fps with the green message, i was able to do this a couple of times but when the game starts, it's still locked at 60 fps, the only setting that's being memorized is the v sync toggle but no fps changes (noticed this after the UI showed on screen again). Once i close the patch, the same thing happens; doesn't show on screen only sits in Windows 11 background processes, then closes /crashes. Only opens after a while when trying to run multiple instances.

**Comment by CadiLillian** [comment] 2023-12-22 19:04
Please read this [post](https://evoweb.uk/threads/efootball-fps-limit-and-vsync-patcher.93599/post-4011199) in the official evoweb thread of the eFootball FPS Limit and VSync Patcher. In particular, the last sentence of that post is relevant to this issue.

Please provide the eFootball MS Store version .exe (3.2.0) [here](https://evoweb.uk/threads/efootball-executable-archive-steam-ms-store.95503/) so that I can resolve this issue.

**Comment by malsalt** [comment] 2023-12-23 10:16
I have posted a download link on the mentioned thread to the dumped file. Thank you

**Comment by CadiLillian** [comment] 2023-12-27 02:25
Thank you very much for providing the dumped MS Store eFootball executable.

The problem you mentioned in this issue is now fixed in [update 2.10](https://github.com/CadiLillian/eFootball-FPS-Limit-and-VSync-Patcher/releases/tag/2.10).
Instead of only fixing this bug for the MS Store version of eFootball 3.2.0, I have identified and fixed the cause of this problem.
This was in fact the same issue as #1.

In addition, related to this issue, [version 2.10](https://github.com/CadiLillian/eFootball-FPS-Limit-and-VSync-Patcher/releases/tag/2.10) introduces a new popup for all eFootball versions without offline/online optimization when the patcher is launched.

**Closed by CadiLillian** 2023-12-27 02:25 UTC
Labels: bug
